<?php

use Fisharebest\Webtrees\GedcomRecord;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\View;
use Fisharebest\Webtrees\Tree;

/**
 * @var string              $module
 * @var array<GedcomRecord> $types
 * @var array<>             $recordTypes
 * @var string              $title
 * @var string              $header_recs
 * @var string              $header_acts
 * @var array<>             $tagsLabels
 * @var string              $tLrouteAjax
 * @var array<>             $tagsXREFs
 * @var Tree                $tree
 */

?>

<h2 class="wt-page-title"><?= $title ?></h2>

<?php if ($recordTypes === []) : ?>
    <h4><?= $header_recs ?></h4>
    <p><?= I18N::translate('Clippings cart is empty.'); ?></p>
<?php else : 
    $html_table = view($module . '::' . 'showTags/showTags-Types', [
        'module'      => $module,
        'types'       => $types,
        'recordTypes' => $recordTypes,
        'title'       => I18N::translate('Family tree clippings cart'),
        'header_recs' => $header_recs,
        'header_acts' => $header_acts,
        'tagsLabels'  => $tagsLabels,
        'tLrouteAjax' => $tLrouteAjax,
        'tagsXREFs'   => $tagsXREFs,
        'tree'        => $tree,
    ]); 
    $html_actions = view($module . '::' . 'showTags/showTags-Actions', [
        
        'module' => $module,
        'header_acts' => $header_acts,
        'tagsLabels'  => $tagsLabels,
        'tLrouteAjax' => $tLrouteAjax,
        'tree'        => $tree
    ]);
    ?>
    <?php echo $html_actions ?>
    <br>
    <p id="prepInfo"><?= I18N::translate("Just a moment") . " ..." ?></p>
    <h4><?= $header_recs ?></h4>
    <?php echo $html_table; ?>
<?php endif; ?>

<?php View::push('styles') ?>
<link rel="stylesheet" href="<?= e($stylesheet) ?>">
<?php View::endpush(); ?>

<?php View::push('javascript'); ?>
<script src="<?= e($javascript); ?>"></script>
<?php View::endpush(); ?>


<?= View::push('javascript'); ?>
<script>
  prepPevents();
  showTables();
</script>
<?= View::endpush(); ?>