<?php

/**
 * webtrees - clippings cart enhanced
 *
 * Copyright (C) 2025 huhwt. All rights reserved.
 *
 */

use Fisharebest\Webtrees\Http\RequestHandlers\MapDataImportAction;
use Fisharebest\Webtrees\Http\RequestHandlers\MapDataList;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;
use Fisharebest\Webtrees\View;

/**
 * @var Tree                $tree
 * @var string              $title
 * @var string              $module
 * @var string              $routeExec
 * @var string              $routeBack
 */

?>

<h2 class="wt-page-title"><?= $title ?></h2>

<form method="post" action="<?= e($routeExec) ?>" id="upload_form" enctype="multipart/form-data">
    <div class="row mb-3">
        <label class="col-form-label col-sm-0" for="import-client-file">
        </label>
        <div class="col-sm-8">
            <input id="import-client-file" type="file" name="client_file" class="form-control" style="font-weight: 800">
        </div>
    </div>

    <div class="row mb-3">
        <label class="col-sm-3" for="line_endings">
            <?= I18N::translate('Line endings') ?>
        </label>
        <div class="col-sm-9">
            <?= view('components/radios-inline', ['name' => 'line_endings', 'options' => ['CRLF' => 'CR/LF (windows)', 'LF' => 'LF (unix)'], 'selected' => 'CRLF']) ?>
        </div>
    </div>

    <div class="row mb-3">
        <label class="col-sm-3" for="separator">
            <?= I18N::translate('Separator') ?>
        </label>
        <div class="col-sm-9">
            <?= view('components/radios-inline', ['name' => 'separator', 'options' => ['semi_colon' => ';', 'comma' => ',', 'tab' => '(tab)'], 'selected' => 'semi_colon']) ?>
        </div>
    </div>

    <div class="row mb-3">
        <label class="col-sm-3" for="enclosure">
            <?= I18N::translate('Enclosure') ?>
        </label>
        <div class="col-sm-9">
            <?= view('components/radios-inline', ['name' => 'enclosure', 'options' => ['none' => '(none)', 'quotation' => '"', 'apostroph' => "'"], 'selected' => 'none']) ?>
        </div>
    </div>

    <div class="row mb-3">
        <label class="col-sm-3" for="escape">
            <?= I18N::translate('Escape') ?>
        </label>
        <div class="col-sm-9">
            <?= view('components/radios-inline', ['name' => 'escape', 'options' => ['backslash' => '\\'], 'selected' => 'backslash']) ?>
        </div>
    </div>

    <!-- SAVE BUTTON -->
    <div class="row mb-3">
        <div class="offset-sm-4 col-sm-8">
            <button type="submit" class="btn btn-primary">
                <?= view('icons/save') ?>
                <?= I18N::translate('continue') ?>
            </button>
            <a href="<?= e($routeBack) ?>">
                <?= view('icons/cancel') ?>
                <?= /* I18N: A button label. */ I18N::translate('cancel') ?>
            </a>
        </div>
    </div>

    <?= csrf_field() ?>
</form>

<?php View::push('javascript') ?>
<script>
  document.getElementById('import-client-file').addEventListener('focus', function () {
    document.getElementById('import-client').checked = true;
  });
</script>
<?php View::endpush() ?>
