<?php

/**
 * webtrees - clippings cart enhanced
 *
 * Copyright (C) 2024 huhwt. All rights reserved.
 *
 */

use Fisharebest\Webtrees\I18N;

/**
 * @var string               $module
 * @var array<string,string> $options
 * //@var array<string,string> $options_ce
 * @var string               $title
 * @var string               $label
 */

?>

<h2 class="wt-page-title"><?= $title ?></h2>

<form method="post" class="wt-page-options wt-page-options-clippings d-print-none">
    <?= csrf_field() ?>

    <div class="row form-group">
        <div class="col-sm-3 col-form-label wt-page-options-label">
            <?= $label ?>
        </div>
        <div class="col-sm-9 wt-page-options-value">
            <?= view('components/radios', ['name' => 'option', 'options' => $options, 'selected' => key($options)]) ?>
            <div>&nbsp;</div>
<!--            < ?= view('components/radios', ['name' => 'option', 'options' => $options_ce, 'selected' => '_NIX_']) ? > -->
        </div>
    </div>

    <div class="row form-group">
        <div class="col-sm-3 wt-page-options-label"></div>
        <div class="col-sm-9 wt-page-options-value">
            <button type="submit" class="btn btn-primary">
                <?= view('icons/save') ?>
                <?= /* I18N: A button label. */ I18N::translate('continue') ?>
            </button>
            <a href="<?= e(route('module', ['module' => $module, 'action' => 'ShowCart', 'tree' => $tree->name()])) ?>" class="btn btn-secondary">
                <?= view('icons/cancel') ?>
                <?= I18N::translate('back to show') ?>
            </a>
        </div>
    </div>
</form>
