<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;
use Fisharebest\Webtrees\Http\RequestHandlers\ModulesAllPage;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;
use Illuminate\Support\Collection;

/**
 * @var array<int,string>    $TAG_options
 * @var int                  $TAGoption
 * @var string               $title
 */

?>

<?= view('components/breadcrumbs', ['links' => [route(ControlPanel::class) => I18N::translate('Control panel'), route(ModulesAllPage::class) => I18N::translate('Modules'), $title]]) ?>

<h1><?= $title ?></h1>
<p>
    <?= I18N::translate('Define the preferred tagging-clause') ?>
</p>

<form method="post">
    <div class="row mb-3">
        <legend class="col-sm-3 col-form-label">
            <?= /* I18N: Configuration option */
            I18N::translate("TAG Definition - Choose a prefix") ?>
        </legend>
        <div class="col-sm-9">
            <?= view('components/radios', ['name' => 'TAGoption', 'selected' => $TAGoption, 'options' => $TAG_options]) ?>
        </div>
    </div>

    <div class="row mb-3">
        <div class="offset-sm-3 col-sm-9">
            <button type="submit" class="btn btn-primary">
                <?= view('icons/save') ?>
                <?= I18N::translate('save') ?>
            </button>
        </div>
    </div>

    <?= csrf_field() ?>
</form>
