<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;
use Fisharebest\Webtrees\Http\RequestHandlers\ModulesAllPage;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;
use Illuminate\Support\Collection;

/**
 * @var string               $title
 * @var string               $line_endings
 * @var string               $separator
 * @var string               $enclosure
 * @var string               $escape
 */

?>

<?= view('components/breadcrumbs', ['links' => [route(ControlPanel::class) => I18N::translate('Control panel'), route(ModulesAllPage::class) => I18N::translate('Modules'), $title]]) ?>

<h1><?= $title ?></h1>
<p>
    <?= I18N::translate('Defaults for saving Clippings Cart XREFs to local CSV file') ?>
</p>

<form method="post">
    <div class="row mb-3">
        <label class="col-sm-4" for="line_endings">
            <?= I18N::translate('To be used for CSV export') . ' ... ' . I18N::translate('Line endings') ?>
        </label>
        <div class="col-sm-8">
            <?= view('components/radios-inline', ['name' => 'line_endings', 'options' => ['CRLF' => 'CR/LF (legacy windows)', 'LF' => 'LF (unix/win10ff/OSX)', 'CR' => 'CR (legacy MacOS)'], 'selected' => $line_endings]) ?>
        </div>
    </div>

    <div class="row mb-3">
        <label class="col-sm-4" for="separator">
            <?= I18N::translate('Separator') ?>
        </label>
        <div class="col-sm-8">
            <?= view('components/radios-inline', ['name' => 'separator', 'options' => ['semi_colon' => ';', 'comma' => ',', 'tab' => '(tab)'], 'selected' => $separator]) ?>
        </div>
    </div>

    <div class="row mb-3">
        <label class="col-sm-4" for="enclosure">
            <?= I18N::translate('Enclosure') ?>
        </label>
        <div class="col-sm-8">
            <?= view('components/radios-inline', ['name' => 'enclosure', 'options' => ['none' => '(none)', 'quotation' => '"', 'apostroph' => "'"], 'selected' => $enclosure]) ?>
        </div>
    </div>

    <div class="row mb-3">
        <label class="col-sm-4" for="escape">
            <?= I18N::translate('Escape') ?>
        </label>
        <div class="col-sm-8">
            <?= view('components/radios-inline', ['name' => 'escape', 'options' => ['backslash' => '\\'], 'selected' => $escape]) ?>
        </div>
    </div>

    <div class="row mb-3">
        <div class="offset-sm-3 col-sm-9">
            <button type="submit" class="btn btn-primary">
                <?= view('icons/save') ?>
                <?= I18N::translate('save') ?>
            </button>
        </div>
    </div>

    <?= csrf_field() ?>
</form>
