<?php

/**
 * webtrees - clippings cart enhanced
 *
 * Copyright (C) 2024 huhwt. All rights reserved.
 *
 */

declare(strict_types=1);

use Fisharebest\Webtrees\Age;
use Fisharebest\Webtrees\Date;
use Fisharebest\Webtrees\Individual;
use Fisharebest\Webtrees\Registry;
use Fisharebest\Webtrees\Family;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Session;
use Fisharebest\Webtrees\Tree;
use Fisharebest\Webtrees\View;
use Illuminate\Support\Collection;


/**
 * @var Tree                    $tree
 * @var Collection<int,Family>  $families
 */

    $dt_jq      = 'const dtFLjq=';

$dt_tabId   = '.wt-table-family';

// EW.H - MOD ... we want the original view-contents
$html = View::make('::lists/families-table', [
    'families' => $families,       // EW.H - MOD ... 
    'tree'     => $tree,
]);
// EW.H - MOD ... and we want to extract the original script-contents
// ... for to catch the datatable declaration for own purpose
$html_s = $this->stack('javascript');
// EW.H - MOD ... there might be multiple scripts included ... 
$html_siT = strpos($html_s,$dt_tabId);                                  // ... so we search for a significant term ...
$html_siS = strrpos(substr($html_s,0, $html_siT),'<script>');               // ... set back to relevant position ...
if (!str_contains($html_s,$dt_jq))
    $html_js = substr($html_s,0,($html_siS+9)).$dt_jq.substr($html_s,($html_siS+9));   // ... and inject the catch
else
    $html_js = $html_s;
// EW.H - MOD ... we define our own script
$table_id_js = 'lists/CCEtable-FL-js';
$html_js1 = View::make($table_id_js, []);

// EW.H - MOD ... we put all together
$html_js .= $html_js1;
// EW.H - MOD ... now we have to restore the script-contents
$this->push('javascript');
echo $html_js;
$this->endpush();

echo $html;
