<?php

/**
 * webtrees - clippings cart enhanced
 *
 * Copyright (C) 2026 huhwt. All rights reserved.
 *
 */

 declare(strict_types=1);

use Fisharebest\Webtrees\Age;
use Fisharebest\Webtrees\Date;
use Fisharebest\Webtrees\Individual;
use Fisharebest\Webtrees\Registry;
use Fisharebest\Webtrees\Family;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Session;
use Fisharebest\Webtrees\Tree;
use Fisharebest\Webtrees\View;
use Illuminate\Support\Collection;


/**
 * @var Collection<int,Individual> $individuals
 * @var array                      $initials
 * @var string                     $title
 * @var Tree                       $tree
 */

 // EW.H - MOD ... we use the original view-contents
$content = View::make('lists/CCElistINDItable', [
    'individuals' => $individuals,  
    'initials'    => $initials,  
    'sosa'        => false,
    'tree'        => $tree,
]);

?>
<h2 class="wt-page-title">
    <?= $title ?>
</h2>

<div class="wt-page-content">
    <?= $content ?>
</div>
