<?php

/**
 * webtrees - clippings cart enhanced
 *
 * Copyright (C) 2024 huhwt. All rights reserved.
 *
 */

declare(strict_types=1);

use Fisharebest\Webtrees\Age;
use Fisharebest\Webtrees\Date;
use Fisharebest\Webtrees\Individual;
use Fisharebest\Webtrees\Registry;
use Fisharebest\Webtrees\Family;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;
use Fisharebest\Webtrees\View;
use Illuminate\Support\Collection;

?>
<!--CCE-Javascript goes here -->
<script>
if (typeof CCEmen === "undefined") {
    var CCEmen = document.querySelector(".CCE_Menue");
    var CCEmenBadge = CCEmen.querySelector("span.badge.bg-secondary");
}
    /* collect option 1 */
var CCEmen_O1 = CCEmen.querySelector("#CCE-Mopt-FL-1");
if (CCEmen_O1)
    CCEprepEvents(CCEmen_O1, dtFLjq, 'wt-table-family');
    /* collect option 2 */
var CCEmen_O2 = CCEmen.querySelector("#CCE-Mopt-FL-2");
if (CCEmen_O2)
    CCEprepEvents(CCEmen_O2, dtFLjq, 'wt-table-family');
    /* collect option 3 */
var CCEmen_O3 = CCEmen.querySelector("#CCE-Mopt-FL-3");
if (CCEmen_O3)
    CCEprepEvents(CCEmen_O3, dtFLjq, 'wt-table-family');
</script>
