<?php

/**
 * webtrees - clippings cart enhanced
 *
 * Copyright (C) 2025 huhwt. All rights reserved.
 *
 */

use Fisharebest\Webtrees\GedcomRecord;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\View;
use Fisharebest\Webtrees\Tree;

/**
 * @var string              $module
 * @var array<GedcomRecord> $types
 * @var array<>             $recordTypes
 * @var string              $title
 * @var string              $ptitle
 * @var string              $header_recs
 * @var string              $header_acts
 * @var array<>             $cartActions
 * @var array<>             $cartActionsFilter
 * @var array<>             $CAfiles
 * @var string              $cArouteAjax
 * @var array<>             $cartXREFs
 * @var Tree                $tree
 */

$html_subheader = view($module . '::' . 'showCart/showCart-subHeader', [
    'header_recs' => '<h4>' . $header_recs . '</h4>',
    'tree'        => $tree,
]);

$cart_empty = $recordTypes === [] ? true : false;
?>

<h2 class="wt-page-title"><?= $ptitle ?></h2>

<?php if ($cart_empty) : ?>
    <?php echo $html_subheader; ?>
    <?= view('modals/ajax') ?>
    <p><?= I18N::translate('Clippings cart is empty.'); ?></p>
<?php else :
    $html_files = view($module . '::' . 'showCart/showCart-CAfiles', [
        'module'      => $module,
        'CAfiles'     => $CAfiles,
        'cArouteAjax' => $cArouteAjax,
        'tree'        => $tree
    ]);
    $html_actions = view($module . '::' . 'showCart/showCart-Actions', [
        'module'      => $module,
        'header_acts' => $header_acts,
        'cartActions' => $cartActions,
        'cArouteAjax' => $cArouteAjax,
        'tree'        => $tree
    ]);
    $html_filter  = view($module . '::' . 'showCart/showCart-ActionsFilter', [
        'module'      => $module,
        'header_filter' => $header_filter,
        'cartActionsFilter' => $cartActionsFilter,
        'cArouteAjax' => $cArouteAjax,
        'tree'        => $tree
    ]);
    $html_table = view($module . '::' . 'showCart/showCart-Types', [
        'module'      => $module,
        'types'       => $types,
        'recordTypes' => $recordTypes,
        'title'       => I18N::translate('Family tree clippings cart'),
        'header_recs' => $header_recs,
        'header_acts' => $header_acts,
        'cartActions' => $cartActions,
        'cArouteAjax' => $cArouteAjax,
        'cartXREFs'   => $cartXREFs,
        'tree'        => $tree,
    ]); 
    ?>
    <?php echo $html_files ?>
    <?php echo $html_actions ?>
    <?php echo $html_filter ?>
    <br>
    <p id="prepInfo"><?= I18N::translate("Just a moment") . " ..." ?></p>
    <h4><?= $header_recs ?></h4>
    <?php echo $html_table; ?>
<?php endif; ?>

<?php View::push('styles') ?>
<link rel="stylesheet" href="<?= e($stylesheet) ?>">
<?php View::endpush(); ?>

<?php View::push('javascript'); ?>
<script src="<?= e($javascript); ?>"></script>
<?php View::endpush(); ?>


<?= View::push('javascript'); ?>
<script>
  CCE_prepPevents();
  CCE_showTables(<?= $cart_empty ?>);
</script>
<?= View::endpush(); ?>