<?php

/**
 * webtrees - clippings cart enhanced
 *
 * Copyright (C) 2024 huhwt. All rights reserved.
 *
 */

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;

use HuHwt\WebtreesMods\ClippingsCartEnhanced\ClippingsCartEnhanced;


/**
 * @var Tree   $tree
 * @var string $title
 * @var string $filenames
 * @var string $SinfoJson
 */
// $Sinfo[]        = I18N::translate('Number of CartActs:');
// $Sinfo[]        = $SinfoAstnew;
// $Sinfo[]        = I18N::translate('of which are new:');
// $Sinfo[]        = $SinfoAstnew - $SinfoAstold;
// $Sinfo[]        = I18N::translate('Number of CartXrefs:');
// $Sinfo[]        = $SinfoCstnew;
// $Sinfo[]        = I18N::translate('of which are new:');
// $Sinfo[]        = $SinfoCstnew - $SinfoCstold;

    $Sinfo      = json_decode($SinfoJson);
    $vCntAtxt   = $Sinfo[0];
    $vCntA      = $Sinfo[1];
    $vCntAtxtn  = $Sinfo[2];
    $vCntAn     = $Sinfo[3];
    $vCntCtxt   = $Sinfo[4];
    $vCntC      = $Sinfo[5];
    $vCntCtxtn  = $Sinfo[6];
    $vCntCn     = $Sinfo[7];

?>
<!--<form method="get" action="< ?= e(route(ClippingsCartEnhanced::class, ['tree' => $tree->name(), 'action' => 'ShowCart'])) ?>" id="wt-modal-form"> -->

    <?= view('modals/header', ['title' => $title]) ?>

    <div class="modal-body">
        <div class="row form-group">
            <div class="col-sm-5 col-form-label wt-page-options-label">
                <span><?= I18N::translate('Filename') . ':' ?></span>
            </div>
            <div class="col-sm-5 wt-page-options-value">
                <?php if( !is_array($filenames) ): ?>
                    <span><?= $filenames ?></span>
                <?php else: ?>
                    <div class="col-sm-9 wt-page-options-value cce-cbul">
                        <ul>
                            <?php foreach ($filenames as $fname) : ?>
                                <li><?= $fname ?></li>
                            <?php endforeach ?>
                        </ul>
                    </div>
                <?php endif ?>
            </div>
        </div>
        <div class="row form-group">
            <div class="col-sm-5 col-form-label wt-page-options-label">
                <span><?= $vCntAtxt ?></span>
            </div>
            <div class="col-sm-5 wt-page-options-value">
                <span><?= $vCntA ?></span>
            </div>
        </div>
        <div class="row form-group">
            <div class="col-sm-5 col-form-label wt-page-options-label">
                <span><?= $vCntAtxtn ?></span>
            </div>
            <div class="col-sm-5 wt-page-options-value">
                <span><?= $vCntAn ?></span>
            </div>
        </div>
        <div class="row form-group">
            <div class="col-sm-5 col-form-label wt-page-options-label">
                <span><?= $vCntCtxt ?></span>
            </div>
            <div class="col-sm-5 wt-page-options-value">
                <span><?= $vCntC ?></span>
            </div>
        </div>
        <div class="row form-group">
            <div class="col-sm-5 col-form-label wt-page-options-label">
                <span><?= $vCntCtxtn ?></span>
            </div>
            <div class="col-sm-5 wt-page-options-value">
                <span><?= $vCntCn ?></span>
            </div>
        </div>
    </div>

    <?= view('modals/footer-checkedCCE') ?>

<!--    < ?= csrf_field() ?>

</form>
                            -->

<script>
    var btnOK = document.getElementById('CCE_btnOK');
    btnOK.addEventListener('click', event => {
        doCCEloaded();
    });
</script>
