<?php

/**
 * webtrees - clippings cart enhanced
 *
 * Copyright (C) 2026 huhwt. All rights reserved.
 *
 */

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;

/**
 * Execute (A)->'Cart-Individuals-As-List' as well as (B)->'Close-The-Modal'
 *
 * will be done by javasript
 * 
 * (A)  routed by a menu element            (B)   triggering the actions behind data-bs-dismiss
 *
 * @var string  $classList
 */

?>

<div class="modal-footer">
    <button type="button" class="btn btn-primary" onclick="click_CCE_btnLIST(<?= $classList ?>)">
        <?= view('icons/save') ?>
        <?= I18N::translate('Execute') ?>
    </button>
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
        <?= view('icons/cancel') ?>
        <?= I18N::translate('cancel') ?>
    </button>
</div>
