<?php

/**
 * webtrees - clippings cart enhanced
 *
 * Copyright (C) 2025 huhwt. All rights reserved.
 *
 */

 declare(strict_types=1);

namespace HuHwt\WebtreesMods\ClippingsCartEnhanced;

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;

use HuHwt\WebtreesMods\ClippingsCartEnhanced\ClippingsCartEnhancedModule;

/**
 * @var Tree    $tree
 */

?>

<form method="post" actionX="<?= $CartLoadAction ?>" id="wt-modal-form">
    <?= view('modals/header', ['title' => I18N::translate('No saved cart files found')]) ?>

    <?= view('modals/footer-backCCE') ?>

    <?= csrf_field() ?>
</form>
