<?php

/**
 * webtrees - clippings cart enhanced
 *
 * Copyright (C) 2024 huhwt. All rights reserved.
 *
 */

use Fisharebest\Webtrees\GedcomRecord;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Registry;
use Fisharebest\Webtrees\View;
use Fisharebest\Webtrees\Tree;

use HuHwt\WebtreesMods\ClippingsCartEnhanced\ClippingsCartEnhancedModule;

/**
 * @var string              $module
 * @var array<GedcomRecord> $types
 * @var array<>             $recordTypes
 * @var string              $title
 * @var string              $header_recs
 * @var string              $header_acts
 * @var array<>             $cartActions
 * @var string              $cArouteAjax
 * @var array<>             $cartXREFs
 * @var Tree                $tree
 */

?>

<div class="input-group">
    <?php $id = Registry::idFactory()->id(); ?>
    <button class="btn btn-secondary cce-btn" type="button" data-bs-toggle="modal" data-bs-backdrop="static" data-bs-target="#wt-ajax-modal" data-wt-href="<?= e(route(ClippingsCartEnhancedModule::class, ['tree' => $tree->name(), 'action' => 'CAload'])) ?>" data-wt-select-id="<?= $id ?>" title="<?= I18N::translate('Load cart from file') ?>">
        <span class="wt-icon-file-import">
            <svg class="fa-solid fa-file-import fa-fw" aria-hidden="true" focusable="false" data-prefix="far" data-icon="file-import" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512" data-fa-i2svg="">
                <path fill="currentColor" d="M128 64c0-35.3 28.7-64 64-64H352V128c0 17.7 14.3 32 32 32H512V448c0 35.3-28.7 64-64 64H192c-35.3 0-64-28.7-64-64V336H302.1l-39 39c-9.4 9.4-9.4 24.6 0 33.9s24.6 9.4 33.9 0l80-80c9.4-9.4 9.4-24.6 0-33.9l-80-80c-9.4-9.4-24.6-9.4-33.9 0s-9.4 24.6 0 33.9l39 39H128V64zm0 224v48H24c-13.3 0-24-10.7-24-24s10.7-24 24-24H128zM512 128H384V0L512 128z">
                </path>
            </svg>
            <!-- <i class="far fa-file-import fa-fw" aria-hidden="true"></i> Font Awesome fontawesome.com -->
        </span>
    </button>
</div>
<?php
