<?php

/**
 * webtrees - clippings cart enhanced
 *
 * Copyright (C) 2024 huhwt. All rights reserved.
 *
 */

use Fisharebest\Webtrees\I18N;

?>

<div class="input-group">
    <button id="btn_Redo" class="btn btn-secondary cce-btn" type="button" title="<?= I18N::translate('Reload') ?>">
        <span class="wt-icon-redo"><i class="fa-solid fa-redo fa-fw" aria-hidden="true"></i></span>
    </button>
</div>
<?php
